s = set()
inp = input("Please enter number: ")
s.add(int(inp))
inp = input("Please enter number: ")
s.add(int(inp))
inp = input("Please enter number: ")
s.add(int(inp))
inp = input("Please enter number: ")
s.add(int(inp))
inp = input("Please enter number: ")
s.add(int(inp))
inp = input("Please enter number: ")
s.add(int(inp))
inp = input("Please enter number: ")
s.add(int(inp))
inp = input("Please enter number: ")
s.add(int(inp))

print(s)
