marks = []

m1 = int(input("Please enter your marks: "))
marks.append(m1)
m2 = int(input("Please enter your marks: "))
marks.append(m2)
m3 = int(input("Please enter your marks: "))
marks.append(m3)
m4 = int(input("Please enter your marks: "))
marks.append(m4)
m5 = int(input("Please enter your marks: "))
marks.append(m5)
m6 = int(input("Please enter your marks: "))
marks.append(m6)
m7 = int(input("please enter your mark: "))
marks.append(m7)
marks.sort()
print(marks)